version: "3.9"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    command: pnpm start:dev
    ports:
      - 3000:3000
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - .env
    command: pnpm dev --host
    ports:
      - 3001:3001

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    # command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_storage:
